[
    {
        userName:'RMKawle',
        passWord:'hashedValue',
        classesConducted:[
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            }
        ]

    },
    {
        userName:'RMKawle',
        passWord:'hashedValue',
        classesConducted:[
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            }
        ]

    },
    {
        userName:'RMKawle',
        passWord:'hashedValue',
        classesConducted:[
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            },
            {
                ClassDetail:'BE',
                Subject:'Maths',
                date:"14/04/2000",
                lectureNo:"21"
            }
        ]

    }
]